type: postgresql
mode: standalone
version:
  postgresql: "18"

cluster:
  instances: 1
  postgresUID: 999
  postgresGID: 999
  postgresql:
    shared_preload_libraries:
      - pg_search
  storage:
    size: 50Gi
  enableSuperuserAccess: true
  monitoring:
    enabled: true
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  imageCatalogRef:
    kind: ImageCatalog
  affinity:
    nodeSelector:
      kubernetes.io/hostname: nuc-i7-gen11.homelab.stephane-klein.info
  initdb:
    database: hindsight
    owner: hindsight

imageCatalog:
  create: true
  images:
    - image: docker.io/paradedb/paradedb:pg18
      major: 18
