ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forwardauth-authelia@kubernetescrd
  hosts:
    - host: perses.sklein.internal
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: perses-tls
      hosts:
        - perses.sklein.internal
persistence:
  enabled: true
  size: 2Gi
sidecar:
  enabled: true
  label: "perses.dev/resource"
  labelValue: "true"
  allNamespaces: true
config:
  frontend:
    important_dashboards:
      - project: homelab
        dashboard: node-overview
      - project: homelab
        dashboard: node-hardware
  provisioning:
    interval: 30s
  security:
    enable_auth: false
    readonly: false
volumes:
  - name: plugins
    emptyDir: {}
volumeMounts:
  - name: plugins
    mountPath: /etc/perses/plugins
