apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-cnpg-memex
spec:
  conditions:
    - namespaces:
        - toggl-pg-mirror
  provider:
    kubernetes:
      remoteNamespace: memex
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        token:
          bearerToken:
            name: external-secrets-k8s-provider-token
            namespace: external-secrets
            key: token
