apiVersion: v1
kind: ConfigMap
metadata:
  name: process-exporter-config
  namespace: monitoring
data:
  config.yml: |
    process_names:
      - name: "{{.Comm}}"
        cmdline:
        - '.+'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: process-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: process-exporter
    app.kubernetes.io/instance: process-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: process-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: process-exporter
        app.kubernetes.io/instance: process-exporter
    spec:
      hostPID: true
      containers:
        - name: process-exporter
          image: ncabatoff/process-exporter:0.8.7
          args:
            - --config.path=/config/config.yml
            - --procfs=/proc
          ports:
            - name: metrics
              containerPort: 9256
          securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: process-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: process-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: process-exporter
    app.kubernetes.io/instance: process-exporter
spec:
  selector:
    app.kubernetes.io/name: process-exporter
  ports:
    - name: metrics
      port: 9256
      targetPort: metrics
