repositories: []
releases:
  - name: toggl-pg-mirror
    namespace: toggl-pg-mirror
    createNamespace: true
    chart: oci://ghcr.io/stephane-klein/charts/toggl-pg-mirror
    version: 0.1.4
    values:
      - values.yaml
