postgresql:
  schema: toggl

cnpg:
  clusterName: memex
  namespace: memex
  secretName: memex-cluster-app
  copySecretName: memex-app

existingSecret:
  name: toggl-pg-mirror
  togglTokenKey: toggl-token
  adminTokenKey: admin-token
  smtpPassKey: smtp-password

smtp:
  host: "smtp.fastmail.com"
  port: 465
  secure: true
  user: "stephane_klein@fastmail.com"
  from: contact@stephane-klein.info
  testTo: "contact@stephane-klein.info"

eso:
  enabled: true
  clusterSecretStoreName: kubernetes-cnpg-memex

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector:
  kubernetes.io/hostname: nuc-i3-gen5.homelab.stephane-klein.info

ingress:
  enabled: true
  className: traefik-public
  hosts:
    - "memex.ipv6.ingress.homelab.public.stephane-klein.info"
    - "memex.sklein.xyz"
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-public
    external-dns.alpha.kubernetes.io/target: "2001:861:8b91:6620::1000"
  tls:
    - secretName: toggl-pg-mirror-tls-public
      hosts:
        - memex.ipv6.ingress.homelab.public.stephane-klein.info
        - memex.sklein.xyz
